version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: your_secure_password
    volumes:
      - ./minio/data:/data
      - ./landing:/data/landing
      - ./raw:/data/raw
      - ./staging:/data/staging
      - ./curated:/data/curated
      - ./archive:/data/archive
      - ./sandbox:/data/sandbox
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
